import settings

# window 
WIDTH = settings.WIDTH
HEIGHT = settings.HEIGHT

# UI
HEALTH_COLOR = 'red'
SHIELD_COLOR = 'blue'
HEALTH_LENGTH = 250
SHIELD_LENGTH = 150
HEALTH_HEIGHT = 20
SHIELD_HEIGHT = 20
BG_COLOR = (20,20,20)

# enemy 
X = WIDTH + 200
ENEMY_NUM = 4

# cooldowns
SCORE_COOLDOWN = 500
ENEMY_INTERVAL = 20
ASTEROID_COOLDOWN = 1800