
# planets
PLANET_NUM = 4
PLANET_SCALES = [0.5,1.5]
PLANET_TYPES = 5

# meteors
METEOR_SCALES = [0.2,0.5]
METEOR_TYPES = 8
A_CONSTANT = 300

# tanks
TANKS_TYPES = 5
HEALTH_BAR_HEIGHT = 3
H_B_COLOR = 'red'
BG_COLOR = (20,20,20)
TANK_HEALTH_BONUS = 50
TANK_NUM_BONUS = 5

# damages
METEOR_TO_TANK_DAMAGE = 33
METEOR_TO_BASE_DAMAGE = 100
FIRE_TO_TANK_DAMAGE = 2
FIRE_TO_BASE_DAMAGE = 2
METEOR_TO_HELIC_DAMAGE = 50

# prices
TANK_PRICE = 150
BALL_PLAYER_PRICE = 2
WATER_PRICE = 50
REPAIR_BASE_PRICE = 150
UPGRADE_BASE_PRICE = 200
UPGRADE_ARMY_PRICE = 250
HELIC_PRICE = 300
EXTINGUISH_FIRES_PRICE = 200

# helicopters 
HELIC_TYPES = 4
HELIC_FRAMES = 3
HELIC_SCALE = 0.7
HELIC_HEALTH_BONUS = 80
HELIC_NUM_BONUS = 2